services:
  - type: web
    name: store
    env: ruby
    plan: free
    buildCommand: |
      bundle install
      yarn install --check-files
      bundle exec rake assets:precompile
      bundle exec rake db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: store-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: NODE_ENV
        value: production

databases:
  - name: store-db
    plan: free
    databaseName: store_production
    user: store_user
